/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as SupervisorUpdateNewRouteImport } from './routes/supervisor-update/new'
import { Route as IssuesNewRouteImport } from './routes/issues/new'
import { Route as IssuesIssueIdRouteImport } from './routes/issues/$issueId'
import { Route as HrUpdateNewRouteImport } from './routes/hr-update/new'
import { Route as GmUpdateNewRouteImport } from './routes/gm-update/new'
import { Route as IssuesIssueIdEditRouteImport } from './routes/issues/$issueId.edit'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorUpdateNewRoute = SupervisorUpdateNewRouteImport.update({
  id: '/supervisor-update/new',
  path: '/supervisor-update/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesNewRoute = IssuesNewRouteImport.update({
  id: '/issues/new',
  path: '/issues/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const HrUpdateNewRoute = HrUpdateNewRouteImport.update({
  id: '/hr-update/new',
  path: '/hr-update/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GmUpdateNewRoute = GmUpdateNewRouteImport.update({
  id: '/gm-update/new',
  path: '/gm-update/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdEditRoute = IssuesIssueIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => IssuesIssueIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/gm-update/new': typeof GmUpdateNewRoute
  '/hr-update/new': typeof HrUpdateNewRoute
  '/issues/$issueId': typeof IssuesIssueIdRouteWithChildren
  '/issues/new': typeof IssuesNewRoute
  '/supervisor-update/new': typeof SupervisorUpdateNewRoute
  '/issues/': typeof IssuesIndexRoute
  '/issues/$issueId/edit': typeof IssuesIssueIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/gm-update/new': typeof GmUpdateNewRoute
  '/hr-update/new': typeof HrUpdateNewRoute
  '/issues/$issueId': typeof IssuesIssueIdRouteWithChildren
  '/issues/new': typeof IssuesNewRoute
  '/supervisor-update/new': typeof SupervisorUpdateNewRoute
  '/issues': typeof IssuesIndexRoute
  '/issues/$issueId/edit': typeof IssuesIssueIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/gm-update/new': typeof GmUpdateNewRoute
  '/hr-update/new': typeof HrUpdateNewRoute
  '/issues/$issueId': typeof IssuesIssueIdRouteWithChildren
  '/issues/new': typeof IssuesNewRoute
  '/supervisor-update/new': typeof SupervisorUpdateNewRoute
  '/issues/': typeof IssuesIndexRoute
  '/issues/$issueId/edit': typeof IssuesIssueIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/security'
    | '/gm-update/new'
    | '/hr-update/new'
    | '/issues/$issueId'
    | '/issues/new'
    | '/supervisor-update/new'
    | '/issues/'
    | '/issues/$issueId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/security'
    | '/gm-update/new'
    | '/hr-update/new'
    | '/issues/$issueId'
    | '/issues/new'
    | '/supervisor-update/new'
    | '/issues'
    | '/issues/$issueId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/security'
    | '/gm-update/new'
    | '/hr-update/new'
    | '/issues/$issueId'
    | '/issues/new'
    | '/supervisor-update/new'
    | '/issues/'
    | '/issues/$issueId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SecurityRoute: typeof SecurityRoute
  GmUpdateNewRoute: typeof GmUpdateNewRoute
  HrUpdateNewRoute: typeof HrUpdateNewRoute
  IssuesIssueIdRoute: typeof IssuesIssueIdRouteWithChildren
  IssuesNewRoute: typeof IssuesNewRoute
  SupervisorUpdateNewRoute: typeof SupervisorUpdateNewRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor-update/new': {
      id: '/supervisor-update/new'
      path: '/supervisor-update/new'
      fullPath: '/supervisor-update/new'
      preLoaderRoute: typeof SupervisorUpdateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/new': {
      id: '/issues/new'
      path: '/issues/new'
      fullPath: '/issues/new'
      preLoaderRoute: typeof IssuesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-update/new': {
      id: '/hr-update/new'
      path: '/hr-update/new'
      fullPath: '/hr-update/new'
      preLoaderRoute: typeof HrUpdateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm-update/new': {
      id: '/gm-update/new'
      path: '/gm-update/new'
      fullPath: '/gm-update/new'
      preLoaderRoute: typeof GmUpdateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId/edit': {
      id: '/issues/$issueId/edit'
      path: '/edit'
      fullPath: '/issues/$issueId/edit'
      preLoaderRoute: typeof IssuesIssueIdEditRouteImport
      parentRoute: typeof IssuesIssueIdRoute
    }
  }
}

interface IssuesIssueIdRouteChildren {
  IssuesIssueIdEditRoute: typeof IssuesIssueIdEditRoute
}

const IssuesIssueIdRouteChildren: IssuesIssueIdRouteChildren = {
  IssuesIssueIdEditRoute: IssuesIssueIdEditRoute,
}

const IssuesIssueIdRouteWithChildren = IssuesIssueIdRoute._addFileChildren(
  IssuesIssueIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SecurityRoute: SecurityRoute,
  GmUpdateNewRoute: GmUpdateNewRoute,
  HrUpdateNewRoute: HrUpdateNewRoute,
  IssuesIssueIdRoute: IssuesIssueIdRouteWithChildren,
  IssuesNewRoute: IssuesNewRoute,
  SupervisorUpdateNewRoute: SupervisorUpdateNewRoute,
  IssuesIndexRoute: IssuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
