/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntriesIndexRouteImport } from './routes/entries/index'
import { Route as EntriesNewRouteImport } from './routes/entries/new'
import { Route as EntriesIdRouteImport } from './routes/entries/$id'
import { Route as EntriesIdEditRouteImport } from './routes/entries/$id.edit'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIndexRoute = EntriesIndexRouteImport.update({
  id: '/entries/',
  path: '/entries/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesNewRoute = EntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdRoute = EntriesIdRouteImport.update({
  id: '/entries/$id',
  path: '/entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdEditRoute = EntriesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EntriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/entries/$id': typeof EntriesIdRouteWithChildren
  '/entries/new': typeof EntriesNewRoute
  '/entries/': typeof EntriesIndexRoute
  '/entries/$id/edit': typeof EntriesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/entries/$id': typeof EntriesIdRouteWithChildren
  '/entries/new': typeof EntriesNewRoute
  '/entries': typeof EntriesIndexRoute
  '/entries/$id/edit': typeof EntriesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/security': typeof SecurityRoute
  '/entries/$id': typeof EntriesIdRouteWithChildren
  '/entries/new': typeof EntriesNewRoute
  '/entries/': typeof EntriesIndexRoute
  '/entries/$id/edit': typeof EntriesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/security'
    | '/entries/$id'
    | '/entries/new'
    | '/entries/'
    | '/entries/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/security'
    | '/entries/$id'
    | '/entries/new'
    | '/entries'
    | '/entries/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/security'
    | '/entries/$id'
    | '/entries/new'
    | '/entries/'
    | '/entries/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SecurityRoute: typeof SecurityRoute
  EntriesIdRoute: typeof EntriesIdRouteWithChildren
  EntriesNewRoute: typeof EntriesNewRoute
  EntriesIndexRoute: typeof EntriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/': {
      id: '/entries/'
      path: '/entries'
      fullPath: '/entries/'
      preLoaderRoute: typeof EntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/new': {
      id: '/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof EntriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id': {
      id: '/entries/$id'
      path: '/entries/$id'
      fullPath: '/entries/$id'
      preLoaderRoute: typeof EntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id/edit': {
      id: '/entries/$id/edit'
      path: '/edit'
      fullPath: '/entries/$id/edit'
      preLoaderRoute: typeof EntriesIdEditRouteImport
      parentRoute: typeof EntriesIdRoute
    }
  }
}

interface EntriesIdRouteChildren {
  EntriesIdEditRoute: typeof EntriesIdEditRoute
}

const EntriesIdRouteChildren: EntriesIdRouteChildren = {
  EntriesIdEditRoute: EntriesIdEditRoute,
}

const EntriesIdRouteWithChildren = EntriesIdRoute._addFileChildren(
  EntriesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SecurityRoute: SecurityRoute,
  EntriesIdRoute: EntriesIdRouteWithChildren,
  EntriesNewRoute: EntriesNewRoute,
  EntriesIndexRoute: EntriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
